language: node_js
os:
  - linux
  - osx
node_js:
  - "6"
  - "7"
install:
  - npm install --build-from-source
  - npm run tsc
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq install g++-4.8 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8 ; fi
script:
  - npm test
  - npm run tslint
deploy:
  provider: releases
  api_key:
    secure: "G+o1GsjLeWq2eiNc8e5wRi9R87TqZXpQMh1qyVknRdsvUW69Mb7QJoSlGvs8FgJlJcty/1DcDN8hab8t0HVLGu0GoaN2KGRT3Hj98SGq75K7lyErPbpxcqF+BTWrrj2mDcOL0LsKvFm8p11nKUNlg4HBNGi885BkiQKuUR3aSS7AcbKoHOoMrpGZum0UjhocsAdefX+Qy44gGSqyppktJVJ8J3LbfK5rSzbVEyWR2MsG/U0dH/LglqaXCeJZrdxo5532zHUoTYyCKsHn5VIVQsPc/De/xGsG/VlPiifJyP/H0Nc7m3jLQjWpgZN7kP/w5ZRohQtbM4SKCXhLmovOsXOen3G+J6H3Ip3yvqZZQZ7DTueDXwjplvuDdfYubDozJwLMP/W+f5ZIaTPkXHAFLIEwqANEDU3KpoOGlJbCcAreVpvnP269041etpP3t0LAezh9WNpHgH6EjapEdQTMCljjwEOjX3C5+uZuuglC782qBoX6w8nkwxWW/5kDY/zo5ZN+ZPsEUN44EfS9bRrqgpj8fi7Bq9jzkCuk57UFH0u6VxQfgCC60B/QcdInunl0yqJafe4fP6pmkv6E5+BPF+1tFyXiqG6Mi0ZAyYlu+8tOEUCv6DcMrto5m6+n8+/7QbRBM+Lh99nntrQ9Nd/TIs9/gQ0WsDZv9qiAtuHnJkI="
  file_glob: true
  file: 'build/stage/**/*.tar.gz'
  skip_cleanup: true
  on:
    tags: true
