environment:
  node_pre_gyp_github_token:
    secure: T7+ogL67i/oZ9pkTUSyItpU7mi0rZKu48QZMGOujQwIANPj1I7oQ1i4qd6tVVAYz
  matrix:
    - nodejs_version: 4
      platform: x64
      msvs_toolset: 12
    # - nodejs_version: 4
    #   platform: x86
    #   msvs_toolset: 12
    - nodejs_version: 5
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 5
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 6
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 6
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 7
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 7
      platform: x86
      msvs_toolset: 12

    - nodejs_version: 6
      platform: x64
      msvs_toolset: 12
      node_target_platform: electron
      node_target_version: 1.3.15
    - nodejs_version: 6
      platform: x86
      msvs_toolset: 12
      node_target_platform: electron
      node_target_version: 1.3.15
    - nodejs_version: 6
      platform: x64
      msvs_toolset: 12
      node_target_platform: electron
      node_target_version: 1.6.9
    - nodejs_version: 6
      platform: x86
      msvs_toolset: 12
      node_target_platform: electron
      node_target_version: 1.6.9

os: Visual Studio 2015

install:
  - scripts\build-appveyor.bat

build: OFF
test: OFF
artifacts:
  - path: 'build\stage\**\*.tar.gz'

deploy_script:
  - ps: |
      If($Env:APPVEYOR_REPO_TAG -eq $true) {
        Write-Debug "Publishing!"
        .\node_modules\.bin\node-pre-gyp-github publish --release
      } Else {
        Write-Debug "Not publishing"
      }
