environment:
  matrix:
    - nodejs_version: 4
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 4
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 5
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 5
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 6
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 6
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 7
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 7
      platform: x86
      msvs_toolset: 12

os: Visual Studio 2015

install:
  - scripts\build-appveyor.bat

build: OFF
test: OFF
artifacts:
  - path: 'build\stage\**\*.tar.gz'
deploy:
  description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
  provider: GitHub
  auth_token:
    secure: T7+ogL67i/oZ9pkTUSyItpU7mi0rZKu48QZMGOujQwIANPj1I7oQ1i4qd6tVVAYz
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
