environment:
  matrix:
    - nodejs_version: 0.10
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 0.10
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 0.12
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 0.12
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 4
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 4
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 5
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 5
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 6
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 6
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 7
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 7
      platform: x86
      msvs_toolset: 12
    # custom visual studio 2015 builds
    - nodejs_version: 0.10.40
      platform: x86
      msvs_toolset: 14
      TOOLSET_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140
    - nodejs_version: 0.10.40
      platform: x64
      msvs_toolset: 14
      TOOLSET_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140
    - nodejs_version: 0.12.7
      platform: x86
      msvs_toolset: 14
      TOOLSET_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140
    - nodejs_version: 0.12.7
      platform: x64
      msvs_toolset: 14
      TOOLSET_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140

os: Visual Studio 2015

install:
  - scripts\build-appveyor.bat

build: OFF
test: OFF
deploy:
  description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
  provider: GitHub
  auth_token:
    secure: a3YsyAKuwI73/fKNBPoXAUbnYOcuY501j3HKbk6VCqfBe9jPHoDIEfyaFNVMQ4a6
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
